### ISSUE TITLE
rebase interattivo

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/helloworld#2]
devi imparare a fare il rebase interattivo

**Comment by Raffaelefrn** [comment]
cos'è il rebase ?

2016-01-27 21:27 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
prima cosa: capire la situazione della nostra repository

prova a dare il comando

``` bash
$ git log --oneline --graph --decorate --all
```

e vedi se ti trovi con me
![schermata da 2016-01-28 21-13-52](https://cloud.githubusercontent.com/assets/3002194/12657543/1a744ee4-c604-11e5-9f8f-eb0d635796d8.png)

ps.
- --oneline permette di stampare un commit per riga
- --graph disegna un grafo con caratteri (al momento poco utile perché non hai diramazioni)
- --all mostra tutte le branch (quando ce ne saranno varie)
- --decorate mostra i nomi delle branch e la posizione del cursore HEAD

**Comment by FabioZTessitore** [comment]
I comandi di cui abbiamo parlato oggi:

``` bash
$ git log --oneline --graph --decorate --all

$ git checkout id_commit

$ git rebase -i id_commit
```

**Comment by FabioZTessitore** [comment]
ci sono problemi con il rebase interattivo?

**Comment by Raffaelefrn** [comment]
non mi ricordo come si faceva a fare con l'editor

2016-01-31 10:16 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
l'editor si apre una prima volta quando ti chiede cosa vuoi fare con i commit. Devi lasciare il primo com'è. Gli altri invece bisogna sostituire pick con squash.
Poi si riapre per la gestione dei messaggi. Deve rimanerne solo uno ovviamente

**Comment by Raffaelefrn** [comment]
sono arrivato qua, poi come devo continuare ?

raffaele@Raffaele-Farina:~$ git log --oneline --graph --decorate --all
- 57bda1d (origin/master) aggiunto tipo di ritorno a main()
- c9b61ad stampa hello wolrd 1.0
- 3743ffe Update hello.c
- bdb6190  stampa hello wolrd
- ec29b2c Initial commit
- a2ef521 (HEAD, master) stampa hello world
- 50fef00  stampa hello world
- 3bc724b  stampa hello world
- 6dd07b7  stampa hello world

Il giorno 31 gennaio 2016 21:11, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
secondo me non hai sostituito pick con squash.
Fai bene se cancelli la tua cartella e ricominci con git clone
